/** Single source of truth for deterministic suggestion scoring. */
export const ACCOUNT_SUGGESTION_CONFIG = Object.freeze({
  algorithmVersion: "deterministic-v7-inference",
  topCandidates: 5,
  minimumSuggestionScore: 45,
  minimumAbsoluteDifference: 8,
  minimumRelativeDifference: 0.12,
  minimumAutomaticConfidence: 0.6,
  scoreForFullConfidence: 100,
  lexicalCandidateThreshold: 0.34,
  semanticEvidence: {
    minimumMediumAliasSimilarity: 0.25,
    minimumMediumJaccardSimilarity: 0.3,
    minimumMediumTrigramSimilarity: 0.2,
    minimumStructuralSignals: 2,
  },
  weights: {
    historicalCompanyMapping: 100,
    exactCompanyAlias: 80,
    exactAlias: 60,
    exactErpTerm: 60,
    exactOfficialName: 55,
    exactAbbreviation: 50,
    exactManualTerm: 55,
    exactIndustryTerm: 50,
    tokenSimilarityMaximum: 30,
    lexicalSimilarityMaximum: 25,
    jaccardMaximum: 24,
    trigramMaximum: 18,
    prefixMaximum: 8,
    conceptMatchMaximum: 24,
    familyMatch: 16,
    termMatch: 10,
    contraAccountMatch: 14,
    compatibleClassification: 15,
    compatibleBalanceNature: 10,
    incompatibleClassification: -50,
    incompatibleBalanceNature: -35,
    exactConceptMatch: 35,
    accountingFamilyMatch: 25,
    statementSectionMatch: 20,
    balanceNatureMatch: 15,
    temporalClassificationMatch: 10,
    conceptContraAccountMatch: 30,
    /** Industry evidence complements (and never replaces) global evidence. */
    industryLearningWeight: 0.25,
    globalLearningMaximum: 30,
    expertLearningMaximum: 30,
  },
});
